In [1]:
import numpy as np
import pandas as pd
import matplotlib as mlt

## Cleaning Customers File

In [2]:
Customers = pd.read_csv('Customers.csv')
Customers.head(10)

,Customer_ID,Customer_Name,Age,Gender,Country,STATE,Email,Phone_Number,Signup_Date
0,C1000,Charvi Sibal,forty two,NaN,India,delhi,nandini30@example.net,9.138190e+11,1/26/2025
1,C1001,Hritik Gala,twenty five,NaN,usa,karnataka,harshildhar@example.com,2.232729e+09,1/15/2024
2,C1002,Adya Sunder,forty two,M,USA,Maharashtra,kritikagade@example.org,5.490818e+09,12/6/2023
3,C1003,Ekiya Palan,twenty five,Fem,usa,tamilnadu,anyamuni@example.net,8.147270e+09,3/28/2022
4,C1004,Vedant Krishna,twenty five,F,USA,karnataka,harrisonshere@example.org,9.148070e+11,2/8/2024
5,C1005,Kashish Subramaniam,twenty five,F,Bharat,Delhi,chakradharsachdev@example.org,9.871558e+08,6/15/2021
6,C1006,Vasana Butala,forty two,female,uk,DL,geetikagopal@example.org,9.180010e+11,11/3/2023
7,C1007,Vivaan Brahmbhatt,twenty five,M,UK,delhi,advik92@example.org,6.441737e+09,5/1/2024
8,C1008,Adya Goswami,19,NaN,Bharat,Tamil Nadu,xluthra@example.org,6.151395e+09,4/16/2021
9,C1009,Manthan Batra,thirty,F,IND,tamilnadu,seshadrimanan@example.org,9.734318e+09,12/11/2025

## Cleaning the Inconsistance Data

In [3]:
# Cleaning Gender Columns
Customers['Gender'].unique()

array([nan, 'M ', 'Fem', 'F', 'female', 'Male'], dtype=object)

In [4]:
Customers['Gender']=Customers['Gender'].str.title().str.strip()
Customers['Gender'].unique()

array([nan, 'M', 'Fem', 'F', 'Female', 'Male'], dtype=object)

In [5]:
Customers['Gender']=Customers['Gender'].replace({'M':'Male','F':'Female','Fem':'Female'})
Customers['Gender'].unique()

array([nan, 'Male', 'Female'], dtype=object)

In [6]:
#Cleaning Country Column
Customers['Country'].unique()

array(['India', 'usa', 'USA', 'Bharat', 'uk', 'UK', 'IND', 'india',
       'Australia', 'australia', 'uae', 'UAE'], dtype=object)

In [7]:
Customers['Country']=Customers['Country'].str.title().str.strip()
Customers['Country'].unique()

array(['India', 'Usa', 'Bharat', 'Uk', 'Ind', 'Australia', 'Uae'],
      dtype=object)

In [8]:
Customers['Country']=Customers['Country'].replace({'Usa':'USA','Bharat':'India','Ind':'India','Uk':'UK','Uae':'UAE'})
Customers['Country'].unique()

array(['India', 'USA', 'UK', 'Australia', 'UAE'], dtype=object)

In [9]:
# Changing Column Name
Customers.rename(columns={'STATE': 'State'}, inplace=True)

In [10]:
#Cleaning The State Columns
Customers['State'].unique()

array(['delhi', 'karnataka', 'Maharashtra', 'tamilnadu', 'Delhi', 'DL',
       'Tamil Nadu', 'TN', 'MH', 'KA', 'maharastra', 'Karnataka'],
      dtype=object)

In [11]:
Customers['State'] = Customers['State'].str.title().str.strip()
Customers['State'].unique()

array(['Delhi', 'Karnataka', 'Maharashtra', 'Tamilnadu', 'Dl',
       'Tamil Nadu', 'Tn', 'Mh', 'Ka', 'Maharastra'], dtype=object)

In [12]:
Customers['State']=Customers['State'].replace({'Dl':'Delhi','Tn':'Tamil Nadu','Tamilnadu':'Tamil Nadu','Maharastra':'Maharashtra',
                                               'Mh':'Maharashtra','Ka':'Karnataka'})
Customers['State'].unique()

array(['Delhi', 'Karnataka', 'Maharashtra', 'Tamil Nadu'], dtype=object)

## Handling missing values

In [13]:
# As 16.9% gender data is null so we can't drop the null 
Customers['Gender'].value_counts()

Gender
Female    19914
Male      13301
Name: count, dtype: int64

In [14]:
#Filling the null values with most repeated values
most_gender = Customers['Gender'].mode()[0]
Customers['Gender']=Customers['Gender'].fillna(most_gender)

In [15]:
Customers.isnull().sum()/len(Customers)*100

Customer_ID      0.0
Customer_Name    0.0
Age              0.0
Gender           0.0
Country          0.0
State            0.0
Email            0.0
Phone_Number     0.0
Signup_Date      0.0
dtype: float64

In [16]:
# Cleaning the Age Columns
Customers['Age'].unique()

array(['forty two', 'twenty five', '19', 'thirty', '51', '24', '46', '29',
       '39', '54', '49', '60', '59', '22', '45', '52', '28', '23', '34',
       '37', '55', '47', '58', '33', '31', '30', '40', '44', '32', '57',
       '18', '26', '38', '42', '56', '20', '48', '27', '50', '21', '25',
       '43', '35', '53', '41', '36'], dtype=object)

In [17]:
# Converting strings into numbers
from word2number import w2n
Customers['Age']=Customers['Age'].apply(lambda x : w2n.word_to_num(x) if isinstance(x,str) else x)

In [18]:
Customers['Age'].unique()

array([42, 25, 19, 30, 51, 24, 46, 29, 39, 54, 49, 60, 59, 22, 45, 52, 28,
       23, 34, 37, 55, 47, 58, 33, 31, 40, 44, 32, 57, 18, 26, 38, 56, 20,
       48, 27, 50, 21, 43, 35, 53, 41, 36])

## Changing the Data Types

In [19]:
#Age Columns object to int
Customers['Age'] = Customers['Age'].astype('int64')

In [20]:
# Date Columns Object to Date
Customers['Signup_Date']=pd.to_datetime(Customers['Signup_Date'])

In [21]:
Customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    40000 non-null  object
 1   Customer_Name  40000 non-null  object
 2   Age            40000 non-null  int64
 3   Gender         40000 non-null  object
 4   Country        40000 non-null  object
 5   State          40000 non-null  object
 6   Email          40000 non-null  object
 7   Phone_Number   40000 non-null  float64
 8   Signup_Date    40000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 2.7+ MB

In [39]:
Customers.head(10)

,Customer_ID,Customer_Name,Age,Gender,Country,State,Email,Phone_Number,Signup_Date
0,C1000,Charvi Sibal,42,Female,India,Delhi,nandini30@example.net,9.138190e+11,2025-01-26
1,C1001,Hritik Gala,25,Female,USA,Karnataka,harshildhar@example.com,2.232729e+09,2024-01-15
2,C1002,Adya Sunder,42,Male,USA,Maharashtra,kritikagade@example.org,5.490818e+09,2023-12-06
3,C1003,Ekiya Palan,25,Female,USA,Tamil Nadu,anyamuni@example.net,8.147270e+09,2022-03-28
4,C1004,Vedant Krishna,25,Female,USA,Karnataka,harrisonshere@example.org,9.148070e+11,2024-02-08
5,C1005,Kashish Subramaniam,25,Female,India,Delhi,chakradharsachdev@example.org,9.871558e+08,2021-06-15
6,C1006,Vasana Butala,42,Female,UK,Delhi,geetikagopal@example.org,9.180010e+11,2023-11-03
7,C1007,Vivaan Brahmbhatt,25,Male,UK,Delhi,advik92@example.org,6.441737e+09,2024-05-01
8,C1008,Adya Goswami,19,Female,India,Tamil Nadu,xluthra@example.org,6.151395e+09,2021-04-16
9,C1009,Manthan Batra,30,Female,India,Tamil Nadu,seshadrimanan@example.org,9.734318e+09,2025-12-11

## Summary

* Cleaned the incorrect formats into single formats using replace
* As there is 16.9%  null gender so we can't drop it so in that case i fill null values with most repeated values in gender
* Some Ages are into word format so by using w2n library conver the words into numbers
* In the end conver age into int64 and shipping date into datetime data type

# Cleaning Product Files

In [22]:
# importing product files

Products = pd.read_csv('products.csv')
Products.head(10)

  Product_ID Product_Name     Category        Price         Cost
0      P1000         rice      Grocery  3046.938364  2425.772522
1      P1001        phone      Fashion  4443.782786  2355.256606
2      P1002        shirt      Fashion  3265.268163   537.243408
3      P1003         Rice  Electronics   -50.000000  2420.537344
4      P1004       laptop      fashion   -50.000000  2211.984915
5      P1005         Rice  Electronics   -50.000000  2019.297723
6      P1006       Laptop  electronics  2957.592560   468.970976
7      P1007       laptop      fashion   -50.000000  1342.466238
8      P1008        Phone  Electronics   -50.000000  1121.642151
9      P1009        Shirt      Grocery  1164.732753  1482.151680

## Cleaning the Inconsistance Data

In [23]:
#Cleaning Product_Name Columns
Products['Product_Name'].unique()

array(['rice', 'phone', 'shirt', 'Rice', 'laptop', 'Laptop', 'Phone',
       'Shirt'], dtype=object)

In [24]:
Products['Product_Name']=Products['Product_Name'].str.title().str.strip()
Products['Product_Name'].unique()

array(['Rice', 'Phone', 'Shirt', 'Laptop'], dtype=object)

In [28]:
#Cleaning Category Columns
Products['Category'].unique()

array(['Grocery', 'Fashion', 'Electronics'], dtype=object)

In [29]:
Products['Category']=Products['Category'].str.title().str.strip()
Products['Category'].unique()

array(['Grocery', 'Fashion', 'Electronics'], dtype=object)

## Cleaning numerical Data Columns

In [30]:
# Correcting the negative values of Price Columns
Products['Price']=Products['Price'].abs()
Products['Price'].describe()

count    40000.000000
mean      1283.195493
std       1600.585055
min         10.095318
25%         50.000000
50%         50.000000
75%       2520.297308
max       4999.683863
Name: Price, dtype: float64

In [31]:
Products[['Price', 'Cost']].describe()

              Price          Cost
count  40000.000000  40000.000000
mean    1283.195493   1502.578149
std     1600.585055    863.229881
min       10.095318      5.048728
25%       50.000000    753.731379
50%       50.000000   1501.817015
75%     2520.297308   2249.430844
max     4999.683863   2999.992177

In [32]:
Products[Products['Cost'] < Products['Price']]

      Product_ID Product_Name     Category        Price         Cost
0          P1000         Rice      Grocery  3046.938364  2425.772522
1          P1001        Phone      Fashion  4443.782786  2355.256606
2          P1002        Shirt      Fashion  3265.268163   537.243408
6          P1006       Laptop  Electronics  2957.592560   468.970976
11         P1011         Rice  Electronics   286.998027    21.406987
...          ...          ...          ...          ...          ...
39989     P40989       Laptop      Grocery  3657.040500  1138.115913
39994     P40994        Shirt  Electronics  1974.236685  1797.152851
39996     P40996        Phone      Grocery  2985.717646   387.156302
39997     P40997         Rice      Grocery  4867.359091   240.504921
39999     P40999        Phone  Electronics  4852.353211  1244.324829

[14323 rows x 5 columns]

In [33]:
#Rounding The Integer values
Products[['Cost', 'Price']]=Products[['Cost', 'Price']].round(2)

#### There are still Some columns which contains Price value greater than Cost Value

In [34]:
## Swaping the values of price with cost where the price is greater than cost 
mask = Products['Cost'] < Products['Price']

Products.loc[mask, ['Price','Cost']] = Products.loc[mask, ['Cost','Price']].values

In [35]:
Products[Products['Cost'] < Products['Price']]

Empty DataFrame
Columns: [Product_ID, Product_Name, Category, Price, Cost]
Index: []

In [36]:
Products[['Price', 'Cost']].describe()

              Price          Cost
count  40000.000000  40000.000000
mean     629.903198   2155.870424
std      816.312366   1224.916442
min        5.050000     35.650000
25%       50.000000   1211.997500
50%       50.000000   2106.905000
75%     1091.895000   2864.530000
max     2999.690000   4999.680000

In [37]:
Products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    40000 non-null  object
 1   Product_Name  40000 non-null  object
 2   Category      40000 non-null  object
 3   Price         40000 non-null  float64
 4   Cost          40000 non-null  float64
dtypes: float64(2), object(3)
memory usage: 1.5+ MB

In [38]:
Products.head(10)

  Product_ID Product_Name     Category    Price     Cost
0      P1000         Rice      Grocery  2425.77  3046.94
1      P1001        Phone      Fashion  2355.26  4443.78
2      P1002        Shirt      Fashion   537.24  3265.27
3      P1003         Rice  Electronics    50.00  2420.54
4      P1004       Laptop      Fashion    50.00  2211.98
5      P1005         Rice  Electronics    50.00  2019.30
6      P1006       Laptop  Electronics   468.97  2957.59
7      P1007       Laptop      Fashion    50.00  1342.47
8      P1008        Phone  Electronics    50.00  1121.64
9      P1009        Shirt      Grocery  1164.73  1482.15

### Summary

* Cleaned the insconsitence data of product name and category by formating the data 
* Convert Negative values to positive by using abs
* Swap all the values of price with cost where price is greated than cost using map

## Cleaning Orders File

In [40]:
#Importing Order files
Orders= pd.read_csv('Orders.csv')
Orders.head(10)

  Order_ID Customer_ID  Order_Date Order_Status Shipping Date
0    O1000      C12603  2020-04-22      Pending    2020-05-04
1    O1001       C3535  2024-08-25    Completed    2024-09-02
2    O1002      C11568  2021-08-27    Cancelled    2021-08-31
3    O1003       C8400  2024-07-13    Completed    2024-07-25
4    O1004      C23777  2020-02-10    Completed    2020-02-14
5    O1005      C11763  2022-10-19      Pending    2022-11-02
6    O1006      C12155  2025-07-31    Cancelled    2025-08-03
7    O1007       C7656  2025-09-13    Completed    2025-09-14
8    O1008       C1643  2023-06-12    Cancelled    2023-06-20
9    O1009      C20581  2023-03-16    Completed    2023-03-25

### Correcting Inconsitance format of Order_Status

In [41]:
# All Posibilites in order_status
Orders['Order_Status'].unique()

array(['Pending', 'Completed', 'Cancelled', 'completed'], dtype=object)

In [42]:
# Formating the text and removing extra space
Orders['Order_Status']=Orders['Order_Status'].str.title().str.strip()
Orders['Order_Status'].unique()

array(['Pending', 'Completed', 'Cancelled'], dtype=object)

### Correcting Data Type OF Order_Date & Shipping Date

In [43]:
#Checking the current Data Type
Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       40000 non-null  object
 1   Customer_ID    40000 non-null  object
 2   Order_Date     40000 non-null  object
 3   Order_Status   40000 non-null  object
 4   Shipping Date  40000 non-null  object
dtypes: object(5)
memory usage: 1.5+ MB

In [44]:
#Converting Object to Date Time Data type
Orders['Order_Date']=pd.to_datetime(Orders['Order_Date'])
Orders['Shipping Date']=pd.to_datetime(Orders['Shipping Date'])

In [45]:
Orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       40000 non-null  object
 1   Customer_ID    40000 non-null  object
 2   Order_Date     40000 non-null  datetime64[ns]
 3   Order_Status   40000 non-null  object
 4   Shipping Date  40000 non-null  datetime64[ns]
dtypes: datetime64[ns](2), object(3)
memory usage: 1.5+ MB

In [46]:
Orders.head(10)

  Order_ID Customer_ID Order_Date Order_Status Shipping Date
0    O1000      C12603 2020-04-22      Pending    2020-05-04
1    O1001       C3535 2024-08-25    Completed    2024-09-02
2    O1002      C11568 2021-08-27    Cancelled    2021-08-31
3    O1003       C8400 2024-07-13    Completed    2024-07-25
4    O1004      C23777 2020-02-10    Completed    2020-02-14
5    O1005      C11763 2022-10-19      Pending    2022-11-02
6    O1006      C12155 2025-07-31    Cancelled    2025-08-03
7    O1007       C7656 2025-09-13    Completed    2025-09-14
8    O1008       C1643 2023-06-12    Cancelled    2023-06-20
9    O1009      C20581 2023-03-16    Completed    2023-03-25

### Summary

* Cleaned the insconsitence data of Order Status by formating the data 
* Convert Shipping Date & Order_Date Data Type from Object to datetime

# Cleaning Order_items Files

In [47]:
#Importing Order_items file
Order_items = pd.read_csv('order_items.csv')
Order_items.head(10)

  Order_Item_ID Order_ID Product_ID  Quantity  Price_per_Unit  Total_Amount
0           OI0   O29876     P24513         3       21.577537     54.732610
1           OI1   O35515      P9928         3      391.407859   1179.223576
2           OI2   O19039     P22714         1      317.881464    322.881464
3           OI3    O4528     P36746         3       51.274048    143.822145
4           OI4   O40524     P24559         4      197.118517    778.474066
5           OI5   O32648     P26140         4      185.709633    747.838530
6           OI6   O10129     P14537         3      322.443128    967.329385
7           OI7   O36529      P2789         3      249.940067    754.820200
8           OI8   O16410     P33731         4      142.377968    559.511873
9           OI9    O6006     P14876         5      142.534535    712.672674

### Correcting the Total_Amount Calculation Error

In [48]:
# Rounding of the Total Amount and Price Per Unit Columns
Order_items[['Total_Amount','Quantity','Price_per_Unit']]=Order_items[['Total_Amount','Quantity','Price_per_Unit']].round(2)

In [49]:
# Checking the values error in columns
Order_items[Order_items['Quantity']*Order_items['Price_per_Unit']!= Order_items['Total_Amount']]

,Order_Item_ID,Order_ID,Product_ID,Quantity,Price_per_Unit,Total_Amount
0,OI0,O29876,P24513,3,21.58,54.73
1,OI1,O35515,P9928,3,391.41,1179.22
2,OI2,O19039,P22714,1,317.88,322.88
3,OI3,O4528,P36746,3,51.27,143.82
4,OI4,O40524,P24559,4,197.12,778.47
...,...,...,...,...,...,...
39994,OI39994,O28016,P7505,4,266.39,1070.56
39995,OI39995,O29009,P13060,2,120.56,246.12
39996,OI39996,O33243,P17453,3,85.57,246.70
39998,OI39998,O10390,P26439,2,105.83,216.65
39999,OI39999,O33535,P3632,3,140.52,426.56

*As Quantity * Price Per Unit is not equal so we have to re-calculate the total Amount column*

In [50]:
# Re Assigning the value
Order_items['Total_Amount']=Order_items['Quantity']*Order_items['Price_per_Unit']

In [51]:
#Re-Checking the condition
Order_items[Order_items['Quantity']*Order_items['Price_per_Unit']!= Order_items['Total_Amount']]

Empty DataFrame
Columns: [Order_Item_ID, Order_ID, Product_ID, Quantity, Price_per_Unit, Total_Amount]
Index: []

In [52]:
Order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_Item_ID   40000 non-null  object
 1   Order_ID        40000 non-null  object
 2   Product_ID      40000 non-null  object
 3   Quantity        40000 non-null  int64
 4   Price_per_Unit  40000 non-null  float64
 5   Total_Amount    40000 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.8+ MB

In [53]:
Order_items.head(10)

  Order_Item_ID Order_ID Product_ID  Quantity  Price_per_Unit  Total_Amount
0           OI0   O29876     P24513         3           21.58         64.74
1           OI1   O35515      P9928         3          391.41       1174.23
2           OI2   O19039     P22714         1          317.88        317.88
3           OI3    O4528     P36746         3           51.27        153.81
4           OI4   O40524     P24559         4          197.12        788.48
5           OI5   O32648     P26140         4          185.71        742.84
6           OI6   O10129     P14537         3          322.44        967.32
7           OI7   O36529      P2789         3          249.94        749.82
8           OI8   O16410     P33731         4          142.38        569.52
9           OI9    O6006     P14876         5          142.53        712.65

### Summary 
* All columns are in correct format.
* After that we simply asign the new values to total amount column to correct the values in it

# Cleaning Payments Files

In [55]:
#Importing Payments File 
Payments = pd.read_csv('payments.csv')
Payments.head(10)

  Payment_ID Order_ID Payment_Date Payment_Method Payment_Status  Amount_Paid
0        PM0   O26974   2022-02-19           Card         Failed  1731.257172
1        PM1    O7829   2020-07-18           card           Paid  2629.996344
2        PM2   O21870   2020-02-04            COD           Paid  4275.022628
3        PM3    O9235   2023-07-29            COD           Paid  3785.645385
4        PM4   O19776   2020-07-21            upi           paid  3146.535505
5        PM5   O30454   2022-04-05           Card           paid  4356.096476
6        PM6   O22638   2025-09-29            COD         Failed  2749.663434
7        PM7    O2454   2023-06-27            UPI         Failed  4343.129267
8        PM8    O3383   2020-04-01            UPI           paid  4647.942138
9        PM9   O24775   2023-09-30            upi           Paid  2357.665830

In [56]:
#Table Info
Payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      40000 non-null  object
 1   Order_ID        40000 non-null  object
 2   Payment_Date    40000 non-null  object
 3   Payment_Method  40000 non-null  object
 4   Payment_Status  40000 non-null  object
 5   Amount_Paid     40000 non-null  float64
dtypes: float64(1), object(5)
memory usage: 1.8+ MB

### Correcting data type

In [57]:
#Changing object to date time type
Payments['Payment_Date']=pd.to_datetime(Payments['Payment_Date'])

In [58]:
# Rounding the value of Amount Paid Columns
Payments['Amount_Paid']=Payments['Amount_Paid'].round(2)

## Cleaning Inconsistance Format

In [59]:
#Checking Inconsistance fromat
for col in Payments.columns:
    if Payments[col].nunique()<20:
        print(Payments[col].value_counts())
        print('-'*40)

Payment_Method
upi     8054
UPI     8016
COD     7997
Card    7973
card    7960
Name: count, dtype: int64
----------------------------------------
Payment_Status
paid      13415
Failed    13391
Paid      13194
Name: count, dtype: int64
----------------------------------------

In [60]:
# Correcting Payment Method
Payments['Payment_Method']=Payments['Payment_Method'].str.title().str.strip()
Payments['Payment_Method'].unique()

array(['Card', 'Cod', 'Upi'], dtype=object)

In [61]:
Payments['Payment_Method']=Payments['Payment_Method'].replace({'Cod':'COD','Upi':'UPI'})
Payments['Payment_Method'].unique()

array(['Card', 'COD', 'UPI'], dtype=object)

In [62]:
# Correcting Payment Status
Payments['Payment_Status']=Payments['Payment_Status'].str.title().str.strip()
Payments['Payment_Status'].unique()

array(['Failed', 'Paid'], dtype=object)

In [63]:
# Re-Checking datatypes
Payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Payment_ID      40000 non-null  object
 1   Order_ID        40000 non-null  object
 2   Payment_Date    40000 non-null  datetime64[ns]
 3   Payment_Method  40000 non-null  object
 4   Payment_Status  40000 non-null  object
 5   Amount_Paid     40000 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 1.8+ MB

In [64]:
#Final table
Payments.head(10)

  Payment_ID Order_ID Payment_Date Payment_Method Payment_Status  Amount_Paid
0        PM0   O26974   2022-02-19           Card         Failed      1731.26
1        PM1    O7829   2020-07-18           Card           Paid      2630.00
2        PM2   O21870   2020-02-04            COD           Paid      4275.02
3        PM3    O9235   2023-07-29            COD           Paid      3785.65
4        PM4   O19776   2020-07-21            UPI           Paid      3146.54
5        PM5   O30454   2022-04-05           Card           Paid      4356.10
6        PM6   O22638   2025-09-29            COD         Failed      2749.66
7        PM7    O2454   2023-06-27            UPI         Failed      4343.13
8        PM8    O3383   2020-04-01            UPI           Paid      4647.94
9        PM9   O24775   2023-09-30            UPI           Paid      2357.67

### Summary 
* All columns are are in correct format.
* All values are unique and non-inconsistance format

# Cleaning Returns Files

In [65]:
#Importing Returns File 
Returns = pd.read_csv('returns.csv')
Returns.head(10)

  Return_ID Order_ID Product_ID Return_Date Return_Reason  Refund_Amount
0        R0    O1699     P13184  2025-06-27       damaged     140.582052
1        R1   O10577     P37295  2020-03-15    Wrong Item     278.028860
2        R2   O34663     P25920  2020-12-25       Damaged     292.496508
3        R3   O39857     P11870  2021-09-27          Late     492.094245
4        R4    O7232     P40318  2023-10-20    Wrong Item     416.244628
5        R5   O36395     P27036  2022-09-10    Wrong Item     179.858417
6        R6   O27523     P16001  2024-09-08       damaged     373.105883
7        R7   O28520     P29736  2022-09-14          Late     420.119045
8        R8   O12696     P29304  2024-07-29       Damaged     102.537946
9        R9   O22511     P10233  2021-11-19       damaged     305.917040

### Correcting the Inconsitancy

In [66]:
# All Unique vallues
Returns['Return_Reason'].unique()

array(['damaged', 'Wrong Item', 'Damaged', 'Late'], dtype=object)

In [67]:
# Cleaning the format
Returns['Return_Reason']=Returns['Return_Reason'].str.title().str.strip()
Returns['Return_Reason'].unique()

array(['Damaged', 'Wrong Item', 'Late'], dtype=object)

In [68]:
# Round figure of Refund_Amount
Returns['Refund_Amount']=Returns['Refund_Amount'].round(2)

### Correcting the Data Type

In [70]:
Returns['Return_Date']=pd.to_datetime(Returns['Return_Date'])

In [71]:
Returns.head(10)

  Return_ID Order_ID Product_ID Return_Date Return_Reason  Refund_Amount
0        R0    O1699     P13184  2025-06-27       Damaged         140.58
1        R1   O10577     P37295  2020-03-15    Wrong Item         278.03
2        R2   O34663     P25920  2020-12-25       Damaged         292.50
3        R3   O39857     P11870  2021-09-27          Late         492.09
4        R4    O7232     P40318  2023-10-20    Wrong Item         416.24
5        R5   O36395     P27036  2022-09-10    Wrong Item         179.86
6        R6   O27523     P16001  2024-09-08       Damaged         373.11
7        R7   O28520     P29736  2022-09-14          Late         420.12
8        R8   O12696     P29304  2024-07-29       Damaged         102.54
9        R9   O22511     P10233  2021-11-19       Damaged         305.92

In [73]:
Returns.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Return_ID      40000 non-null  object
 1   Order_ID       40000 non-null  object
 2   Product_ID     40000 non-null  object
 3   Return_Date    40000 non-null  datetime64[ns]
 4   Return_Reason  40000 non-null  object
 5   Refund_Amount  40000 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 1.8+ MB

### Summary 
* All columns are are in correct format.
* All values are unique and non-inconsistance format

# Cleaning Returns Files

In [88]:
#Importing Returns File 
Reviews = pd.read_csv('reviews.csv')
Reviews.head(10)

  Review_id Customer_id Product_id  Rating Review text review date
0       RV0      C26263     P31065       5     Average  2024-09-24
1       RV1      C15009     P36269       5        poor  2021-01-21
2       RV2      C12865     P25031       3        Good  2023-02-20
3       RV3       C9560     P29466       3         bad  2023-01-19
4       RV4      C37926     P22717       4     Average  2025-03-17
5       RV5      C14029     P34178       2         bad  2023-07-02
6       RV6      C11818      P4536       5     Average  2020-11-07
7       RV7      C10365      P1406       3        Good  2025-06-20
8       RV8      C25722     P22302       1   excellent  2021-10-31
9       RV9      C32739     P17123       1        Good  2020-01-13

In [89]:
#Renaming the column name
Reviews=Reviews.rename(columns={'Review text':'Review_Text'})
Reviews=Reviews.rename(columns={'review date':'Review_Date'})

### Correcting the Data Type

In [90]:
Reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review_id    40000 non-null  object
 1   Customer_id  40000 non-null  object
 2   Product_id   40000 non-null  object
 3   Rating       40000 non-null  int64
 4   Review_Text  40000 non-null  object
 5   Review_Date  40000 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.8+ MB

In [91]:
Reviews['Review_Date']=pd.to_datetime(Reviews['Review_Date'])

### Correcting the Inconsitancy

In [92]:
Reviews['Review_Text'].unique()

array(['Average', 'poor', 'Good', 'bad', 'excellent'], dtype=object)

In [94]:
#Correcting format
Reviews['Review_Text']=Reviews['Review_Text'].str.title().str.strip()
Reviews['Review_Text'].unique()

array(['Average', 'Poor', 'Good', 'Bad', 'Excellent'], dtype=object)

In [95]:
Reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review_id    40000 non-null  object
 1   Customer_id  40000 non-null  object
 2   Product_id   40000 non-null  object
 3   Rating       40000 non-null  int64
 4   Review_Text  40000 non-null  object
 5   Review_Date  40000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.8+ MB

In [96]:
Reviews.head(10)

  Review_id Customer_id Product_id  Rating Review_Text Review_Date
0       RV0      C26263     P31065       5     Average  2024-09-24
1       RV1      C15009     P36269       5        Poor  2021-01-21
2       RV2      C12865     P25031       3        Good  2023-02-20
3       RV3       C9560     P29466       3         Bad  2023-01-19
4       RV4      C37926     P22717       4     Average  2025-03-17
5       RV5      C14029     P34178       2         Bad  2023-07-02
6       RV6      C11818      P4536       5     Average  2020-11-07
7       RV7      C10365      P1406       3        Good  2025-06-20
8       RV8      C25722     P22302       1   Excellent  2021-10-31
9       RV9      C32739     P17123       1        Good  2020-01-13

### Summary 
* All columns are are in correct format with correct columns name.
* All values are unique and non-inconsistance format

## Saving All The Cleaned Files in One Cleand_Data folder

In [98]:
import os

In [99]:
import os

os.makedirs("cleaned_data", exist_ok=True)

Customers.to_csv("cleaned_data/Customers.csv", index=False)
Products.to_csv("cleaned_data/Products.csv", index=False)
Orders.to_csv("cleaned_data/Orders.csv", index=False)
Order_items.to_csv("cleaned_data/Order_items.csv", index=False)
Payments.to_csv("cleaned_data/Payments.csv", index=False)
Returns.to_csv("cleaned_data/Returns.csv", index=False)
Reviews.to_csv("cleaned_data/Reviews.csv", index=False)